version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: moxfield-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: moxfield

volumes:
  mongo-data:
